name: Update Sun Calendar

on:
  # This uses cron to schedule the action.
  # '0 0 * * MON' = at 00:00 UTC every Monday.
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Step 1: Give the workflow permission to push code
    permissions:
      contents: write

    steps:
      # Step 2: Check out your code
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # IMPORTANT: This ensures we can push changes back
          persist-credentials: false

      # Step 3: Configure git for pushing using the GITHUB_TOKEN
      - name: Set up git for push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Authenticate for git push
        run: |
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          git config credential.helper 'store --file=~/.git-credentials'

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 5: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install requests ics pytz

      # Step 6: Run your script
      - name: Generate ICS file
        run: |
          python create_calendar_local.py

      # Step 7: (Optional) Move `sun.ics` to docs/ if GH Pages expects it there
      # - name: Move ICS to docs
      #   run: mv sun.ics docs/

      # Step 8: Commit and push changes back to repository
      - name: Commit and push changes
        run: |
          git add sun.ics
          git commit -m "Update sun.ics [skip ci]" || echo "No changes to commit"
          git push
